함수 -> 모듈 -> 패키지 -> 라이브러리
패키지와 라이브러리를 묶어서 패키지라고 보통 이야기 함
이 패키지에는 pytorch / tensorflow 등이 있음

이 패키지는 설치가 되어있는게 있고 설치해야 하는게 있음


In [6]:
import tensorflow as tf
#tensorflow의 abc
#tensorflow.abc() 로 사용 필요
#import 패키지명 as 별명
tf.abc()

AttributeError: module 'tensorflow' has no attribute 'abc'

In [7]:
import numpy as np
np.array ([1,2])

from numpy import array
array([1,2])

array([1, 2])

In [9]:
from pandas import DataFrame
DataFrame

pandas.core.frame.DataFrame

In [10]:
!pip3 install mlxtend

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 8.8 MB/s eta 0:00:00ta 0:00:01
  Obtaining dependency information for matplotlib>=3.0.0 from https://files.pythonhosted.org/packages/8d/22/719f4fff33b13b0708711fb52ca3fc44617a26728e0e023358288d5197ae/matplotlib-3.7.2-cp310-cp310-macosx_11_0_arm64.whl.metadata
  Obtaining dependency information for contourpy>=1.0.1 from https://files.pythonhosted.org/packages/15/c4/aae3954fce0e22362cc55430d1a395bf0be5a22b40fce63edda9eb6ea339/contourpy-1.1.0-cp310-cp310-macosx_11_0_arm64.whl.metadata
  Obtaining dependency information for fonttools>=4.22.0 from https://files.pythonhosted.org/packages/50/d1/9b33abce8c6484ed164c6c548912079e02f8935ca3a4b65d5013ddf7bc0c/fonttools-4.42.0-cp310-cp310-macosx_10_9_universal2.whl.metadata
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.6/150.6 kB 9.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.2/63.2 kB 8.0 MB/s eta 0:00:00
  Obtaining dependency information for pillow>=6.2.0 from htt

많이 사용하는 패키지
*numpy       수치
pandas      1D / 2D 지원
*sklearn     머신러닝관련 기본
statmodels  통계모형 제공
matplotlib  시각화
*seaborn     시각화


In [16]:
import numpy as np

a = np.array( [0,1,2,3,4,5])
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a)
print(a*3) # 숫자계산이 됨


1
(6,)
int64
[0 1 2 3 4 5]
[ 0  3  6  9 12 15]


In [22]:
a2 = np.array( [[0,1,2],[3,4,5]] )
a2 # 2차원 어레이가 생성됨
print(a2.shape)
print(a2.dtype)

(2, 3)
int64


In [24]:
a = np.array( [0,1,2,3,4,5])
b = a.reshape([3,2])


array([[0, 1],
       [2, 3],
       [4, 5]])

In [27]:
a = np.array( [0,1,2,3,4,5,6,7])
c = a.reshape([2,2,2,1])
c


array([[[[0],
         [1]],

        [[2],
         [3]]],


       [[[4],
         [5]],

        [[6],
         [7]]]])

In [31]:
c1 = np.array([1,2,3,4])
c2 = np.array([5,6,7,8])
#c1, c2 를 각가 2d,두개를 곱해주세요

c1r= c1.reshape([2,2])
c2r= c2.reshape([2,2])

c1r*c2r   # 행렬곱 아님
#c1r.dot(c2r) == np.matmul(c1r, c2r)
#np.matmul(c1r, c2r)


array([[19, 22],
       [43, 50]])

In [46]:
a = np.array( [0,1,2,3,4,5])
print(a[[0,2]])

print (a[0:3]) #슬라이싱

print(a[[False, True, False, False, False, False]])
print(a>3)
print (a[a>3])

#a[a>4] = 4 
#a

print(a.tolist)
print(a.max())
print(a.mean())
print(a.argmax())

[0 2]
[0 1 2]
[1]
[False False False False  True  True]
[4 5]
<built-in method tolist of numpy.ndarray object at 0x17a9d72d0>
5
2.5
5


In [62]:
d1 = np.array([1,3,5,6,8,6,3,7])
d2 = d1.reshape([4,2])
print("d2", d2)
print("1,3행, 2열", d2[[0,2],1])
print("2~4행, 1,2열", d2[1:4,:])
print("1열", d2[:,0])
print("1열>4 인 행", d2[d2[:,0]>4, :])

d2 [[1 3]
 [5 6]
 [8 6]
 [3 7]]
1,3행, 2열 [3 6]
2~4행, 1,2열 [[5 6]
 [8 6]
 [3 7]]
1열 [1 5 8 3]
1열>4 인 행 [[5 6]
 [8 6]]


In [70]:
print(d2)
print(d2.argmax(axis=0)) #열에서
print(d2.argmax(axis=-1)) #행에서


[[1 3]
 [5 6]
 [8 6]
 [3 7]]
[2 3]
[1 1 0 1]


In [72]:
#슬라이싱
arr = np.arange(10, dtype=float).reshape((2, 5))
print(arr)
print(arr[0]) # 0번째 원소
print(arr[0, 3]) # 0행 3열
print(arr[0][3]) # 0행3열

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[0. 1. 2. 3. 4.]
3.0
3.0


In [75]:
x= np.reshape(np.arange(20.0),(4,5))
print (x)
print(np.mean(x,0)) #컬럼단위로 계산

print(np.median(x))

print(np.std(x))
print(np.var(x))


[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]
[ 7.5  8.5  9.5 10.5 11.5]
9.5
5.766281297335398
33.25


In [76]:
import pandas as pd


In [78]:
df1 = pd.read_csv("./data/creditset.csv") #데이타프레임


In [79]:
df1
#values = 2d array
#index = 행
#columns = 열


clientid        income        age         loan       LTI  default10yr
0            1  66155.925095  59.017015  8106.532131  0.122537            0
1            2  34415.153966  48.117153  6564.745018  0.190752            0
2            3  57317.170063  63.108049  8020.953296  0.139940            0
3            4  42709.534201  45.751972  6103.642260  0.142911            0
4            5  66952.688845  18.584336  8770.099235  0.130989            1
...        ...           ...        ...          ...       ...          ...
1995      1996  59221.044874  48.518179  1926.729397  0.032535            0
1996      1997  69516.127573  23.162104  3503.176156  0.050394            0
1997      1998  44311.449262  28.017167  5522.786693  0.124636            1
1998      1999  43756.056605  63.971796  1622.722598  0.037086            0
1999      2000  69436.579552  56.152617  7378.833599  0.106267            0

[2000 rows x 6 columns]

In [84]:
#df1.values
#df1.columns
df1.index
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   clientid     2000 non-null   int64  
 1   income       2000 non-null   float64
 2   age          2000 non-null   float64
 3   loan         2000 non-null   float64
 4   LTI          2000 non-null   float64
 5   default10yr  2000 non-null   int64  
dtypes: float64(4), int64(2)
memory usage: 93.9 KB


In [83]:
df1.describe()

clientid        income          age          loan          LTI  \
count  2000.000000   2000.000000  2000.000000   2000.000000  2000.000000   
mean   1000.500000  45331.600018    40.927143   4444.369695     0.098403   
std     577.494589  14326.327119    13.262450   3045.410024     0.057620   
min       1.000000  20014.489470    18.055189      1.377630     0.000049   
25%     500.750000  32796.459717    29.062492   1939.708847     0.047903   
50%    1000.500000  45789.117313    41.382673   3974.719419     0.099437   
75%    1500.250000  57791.281668    52.596993   6432.410625     0.147585   
max    2000.000000  69995.685578    63.971796  13766.051239     0.199938   

       default10yr  
count  2000.000000  
mean      0.141500  
std       0.348624  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       0.000000  
max       1.000000

In [89]:
#adv.values(2d array)에서 첫번째 컬럼이 두번째 컬럼의 평균보다 큰 행을 선택하여 출력
df2=pd.read_csv("./data/adv.csv")
df2

Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [86]:
df2.describe()

Unnamed: 0          TV       radio   newspaper       sales
count  200.000000  200.000000  200.000000  200.000000  200.000000
mean   100.500000  147.042500   23.264000   30.554000   14.022500
std     57.879185   85.854236   14.846809   21.778621    5.217457
min      1.000000    0.700000    0.000000    0.300000    1.600000
25%     50.750000   74.375000    9.975000   12.750000   10.375000
50%    100.500000  149.750000   22.900000   25.750000   12.900000
75%    150.250000  218.825000   36.525000   45.100000   17.400000
max    200.000000  296.400000   49.600000  114.000000   27.000000

In [110]:
df2a = df2.values
df2_mean = df2a[:,1].mean()
print(df2_mean)
df2a[ df2a[:,1]>df2_mean,:]

147.0425


array([[  1. , 230.1,  37.8,  69.2,  22.1],
       [  4. , 151.5,  41.3,  58.5,  18.5],
       [  5. , 180.8,  10.8,  58.4,  12.9],
       [ 10. , 199.8,   2.6,  21.2,  10.6],
       [ 12. , 214.7,  24. ,   4. ,  17.4],
       [ 15. , 204.1,  32.9,  46. ,  19. ],
       [ 16. , 195.4,  47.7,  52.9,  22.4],
       [ 18. , 281.4,  39.6,  55.8,  24.4],
       [ 20. , 147.3,  23.9,  19.1,  14.6],
       [ 21. , 218.4,  27.7,  53.4,  18. ],
       [ 22. , 237.4,   5.1,  23.5,  12.5],
       [ 24. , 228.3,  16.9,  26.2,  15.5],
       [ 26. , 262.9,   3.5,  19.5,  12. ],
       [ 28. , 240.1,  16.7,  22.9,  15.9],
       [ 29. , 248.8,  27.1,  22.9,  18.9],
       [ 31. , 292.9,  28.3,  43.2,  21.4],
       [ 34. , 265.6,  20. ,   0.3,  17.4],
       [ 36. , 290.7,   4.1,   8.5,  12.8],
       [ 37. , 266.9,  43.8,   5. ,  25.4],
       [ 40. , 228. ,  37.7,  32. ,  21.5],
       [ 41. , 202.5,  22.3,  31.6,  16.6],
       [ 42. , 177. ,  33.4,  38.7,  17.1],
       [ 43. , 293.6,  27.7,   1

In [111]:
df2.columns

df2.TV
df2["TV"]
df2.iloc[:,1] #iloc[array스타일 인덱싱, 슬라이싱]

0      230.1
1       44.5
2       17.2
3      151.5
4      180.8
       ...  
195     38.2
196     94.2
197    177.0
198    283.6
199    232.1
Name: TV, Length: 200, dtype: float64

In [116]:
#TV, radio 칼럼 선택
df2[["TV","radio"]] # 필요 컬러명을 list로 묶어서 인덱싱
df2.iloc[:,1:3] #array 처럼 indexing, slicing

TV  radio
0    230.1   37.8
1     44.5   39.3
2     17.2   45.9
3    151.5   41.3
4    180.8   10.8
..     ...    ...
195   38.2    3.7
196   94.2    4.9
197  177.0    9.3
198  283.6   42.0
199  232.1    8.6

[200 rows x 2 columns]

In [119]:
#df2에서 sales라는 컬럼 제외
df2.drop("sales", axis=1) #axis=1 은 컬럼을 삭제

Unnamed: 0     TV  radio  newspaper
0             1  230.1   37.8       69.2
1             2   44.5   39.3       45.1
2             3   17.2   45.9       69.3
3             4  151.5   41.3       58.5
4             5  180.8   10.8       58.4
..          ...    ...    ...        ...
195         196   38.2    3.7       13.8
196         197   94.2    4.9        8.1
197         198  177.0    9.3        6.4
198         199  283.6   42.0       66.2
199         200  232.1    8.6        8.7

[200 rows x 4 columns]

In [124]:
#df1에서 loan, age, income 컬럼을 두가지 방법으로 선택
print(df1[["loan", "age", 'income']])
print(df1.iloc[:,1:4])

             loan        age        income
0     8106.532131  59.017015  66155.925095
1     6564.745018  48.117153  34415.153966
2     8020.953296  63.108049  57317.170063
3     6103.642260  45.751972  42709.534201
4     8770.099235  18.584336  66952.688845
...           ...        ...           ...
1995  1926.729397  48.518179  59221.044874
1996  3503.176156  23.162104  69516.127573
1997  5522.786693  28.017167  44311.449262
1998  1622.722598  63.971796  43756.056605
1999  7378.833599  56.152617  69436.579552

[2000 rows x 3 columns]
            income        age         loan
0     66155.925095  59.017015  8106.532131
1     34415.153966  48.117153  6564.745018
2     57317.170063  63.108049  8020.953296
3     42709.534201  45.751972  6103.642260
4     66952.688845  18.584336  8770.099235
...            ...        ...          ...
1995  59221.044874  48.518179  1926.729397
1996  69516.127573  23.162104  3503.176156
1997  44311.449262  28.017167  5522.786693
1998  43756.056605  63.971796

In [122]:
#df1에서 default10yr컬럼 삭제한 결과 출력
df1.drop("default10yr", axis=1)

clientid        income        age         loan       LTI
0            1  66155.925095  59.017015  8106.532131  0.122537
1            2  34415.153966  48.117153  6564.745018  0.190752
2            3  57317.170063  63.108049  8020.953296  0.139940
3            4  42709.534201  45.751972  6103.642260  0.142911
4            5  66952.688845  18.584336  8770.099235  0.130989
...        ...           ...        ...          ...       ...
1995      1996  59221.044874  48.518179  1926.729397  0.032535
1996      1997  69516.127573  23.162104  3503.176156  0.050394
1997      1998  44311.449262  28.017167  5522.786693  0.124636
1998      1999  43756.056605  63.971796  1622.722598  0.037086
1999      2000  69436.579552  56.152617  7378.833599  0.106267

[2000 rows x 5 columns]