함수 -> 모듈 -> 패키지 -> 라이브러리
패키지와 라이브러리를 묶어서 패키지라고 보통 이야기 함
이 패키지에는 pytorch / tensorflow 등이 있음

이 패키지는 설치가 되어있는게 있고 설치해야 하는게 있음


In [6]:
import tensorflow as tf
#tensorflow의 abc
#tensorflow.abc() 로 사용 필요
#import 패키지명 as 별명
tf.abc()

AttributeError: module 'tensorflow' has no attribute 'abc'

In [7]:
import numpy as np
np.array ([1,2])

from numpy import array
array([1,2])

array([1, 2])

In [9]:
from pandas import DataFrame
DataFrame

pandas.core.frame.DataFrame

In [10]:
!pip3 install mlxtend

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 8.8 MB/s eta 0:00:00ta 0:00:01
  Obtaining dependency information for matplotlib>=3.0.0 from https://files.pythonhosted.org/packages/8d/22/719f4fff33b13b0708711fb52ca3fc44617a26728e0e023358288d5197ae/matplotlib-3.7.2-cp310-cp310-macosx_11_0_arm64.whl.metadata
  Obtaining dependency information for contourpy>=1.0.1 from https://files.pythonhosted.org/packages/15/c4/aae3954fce0e22362cc55430d1a395bf0be5a22b40fce63edda9eb6ea339/contourpy-1.1.0-cp310-cp310-macosx_11_0_arm64.whl.metadata
  Obtaining dependency information for fonttools>=4.22.0 from https://files.pythonhosted.org/packages/50/d1/9b33abce8c6484ed164c6c548912079e02f8935ca3a4b65d5013ddf7bc0c/fonttools-4.42.0-cp310-cp310-macosx_10_9_universal2.whl.metadata
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.6/150.6 kB 9.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.2/63.2 kB 8.0 MB/s eta 0:00:00
  Obtaining dependency information for pillow>=6.2.0 from htt

많이 사용하는 패키지
*numpy       수치
pandas      1D / 2D 지원
*sklearn     머신러닝관련 기본
statmodels  통계모형 제공
matplotlib  시각화
*seaborn     시각화


In [16]:
import numpy as np

a = np.array( [0,1,2,3,4,5])
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a)
print(a*3) # 숫자계산이 됨


1
(6,)
int64
[0 1 2 3 4 5]
[ 0  3  6  9 12 15]


In [22]:
a2 = np.array( [[0,1,2],[3,4,5]] )
a2 # 2차원 어레이가 생성됨
print(a2.shape)
print(a2.dtype)

(2, 3)
int64


In [24]:
a = np.array( [0,1,2,3,4,5])
b = a.reshape([3,2])


array([[0, 1],
       [2, 3],
       [4, 5]])

In [27]:
a = np.array( [0,1,2,3,4,5,6,7])
c = a.reshape([2,2,2,1])
c


array([[[[0],
         [1]],

        [[2],
         [3]]],


       [[[4],
         [5]],

        [[6],
         [7]]]])

In [31]:
c1 = np.array([1,2,3,4])
c2 = np.array([5,6,7,8])
#c1, c2 를 각가 2d,두개를 곱해주세요

c1r= c1.reshape([2,2])
c2r= c2.reshape([2,2])

c1r*c2r   # 행렬곱 아님
#c1r.dot(c2r) == np.matmul(c1r, c2r)
#np.matmul(c1r, c2r)


array([[19, 22],
       [43, 50]])

In [46]:
a = np.array( [0,1,2,3,4,5])
print(a[[0,2]])

print (a[0:3]) #슬라이싱

print(a[[False, True, False, False, False, False]])
print(a>3)
print (a[a>3])

#a[a>4] = 4 
#a

print(a.tolist)
print(a.max())
print(a.mean())
print(a.argmax())

[0 2]
[0 1 2]
[1]
[False False False False  True  True]
[4 5]
<built-in method tolist of numpy.ndarray object at 0x17a9d72d0>
5
2.5
5


In [62]:
d1 = np.array([1,3,5,6,8,6,3,7])
d2 = d1.reshape([4,2])
print("d2", d2)
print("1,3행, 2열", d2[[0,2],1])
print("2~4행, 1,2열", d2[1:4,:])
print("1열", d2[:,0])
print("1열>4 인 행", d2[d2[:,0]>4, :])

d2 [[1 3]
 [5 6]
 [8 6]
 [3 7]]
1,3행, 2열 [3 6]
2~4행, 1,2열 [[5 6]
 [8 6]
 [3 7]]
1열 [1 5 8 3]
1열>4 인 행 [[5 6]
 [8 6]]


In [68]:
print(d2)
d2.argmax(axis=0) #열에서
d2.argmax(axis=-1) #행에서


[[1 3]
 [5 6]
 [8 6]
 [3 7]]


array([2, 3])